# Automation with pyautogui: a song to troll people who come to deceive
import time
import pyautogui

song = [("At first I was afraid,", 15),
        ("I was petrified", 1),
        ("Thinking I could live without you by my side", 1),
        ("And after spending nights", 1),
        ("Thinking how you did me wrong", 1),
        ("I grew strong", 1),
	    ("And I learned how to get along", 1),
	    ("Now you re back", 1),
	    ("From outer space", 1),
	    ("And I find you here", 1),
	    ("With that sad look upon your face", 1),
	    ("WI should ve changed that stupid lock", 1),
	    ("Or made you leave your key", 1),
	    ("If I'd ve known for a second", 1),
        ("You'd be back to bother me", 1),
	    ("Go on, go, walk out the door", 1),
	    ("Turn around now", 1),
	    ("You're the one who tried to hurt me with goodbye", 1),
	    ("Think I'd crumble?", 1),
	    ("You think I'd lay down and die?", 1),
	    ("No, not I, I will survive", 1),
	    ("Long as I know how to love, I know I'll stay alive", 1),
	    ("I ve got my life to live", 1),
	    ("And all my love to give and", 1),
	    ("I will survive", 1),
	    ("♪", 1),
	    ("It took all my strength not to fall apart", 1),
	    ("Trying with all my might to mend my broken heart", 1),
	    ("I spent so many nights feeling sorry for myself", 1),
	    ("How I cried", 1),
	    ("But now I hold my head up high", 1),
	    ("And you see me, somebody new", 1),
	    ("I'm not that lonely little person", 1),
	    ("Still in love with you", 1),
	    ("Now you come droppin' in", 1),
	    ("Expectin' me to be free", 1),
	    ("Now I'm saving my lovin'", 1),
	    ("For someone who's loving me", 1),
	    ("Go on and go, walk out the door", 1),
	    ("Turn around now", 1),
	    ("You're not welcome anymore", 1),
	    ("You're the one who tried to hurt me with goodbye", 1),
	    ("Thinkin' I'd crumble", 1),
	    ("Did you think I'd lay down and die?", 1),
	    ("No, not I, I will survive", 1),
	    ("Long as I know how to love, I know I'll stay alive", 1),
	    ("I've got my life to live, and all my love to give", 1),
	    ("And I will survive", 1),
	    ("I, I will survive", 1),
	    ("Go on, go, walk out the door", 1),
	    ("Turn around now", 1),
	    ("You're not welcome anymore", 1),
	    ("You're the one who tried to hurt me with goodbye", 1),
	    ("Think I'd crumble?", 1),
	    ("You think I'd lay down and die?", 1),
	    ("No, not I, I will survive", 1),
	    ("Long as I know how to love", 1),
	    ("I know I'll stay alive", 1),
	    ("I've got my life to live", 1),
	    ("And all my love to give and", 1),
	    ("I will survive", 1),
	    ("I, I, I will survive", 1),
	    ("♪", 1), # . . .
    ]

for estrofa in song:
    pyautogui.write(estrofa[0])
    time.sleep(estrofa[1])
    pyautogui.press("enter")